### ISSUE TITLE
Removing Console.log from client side

### ISSUE THREAD

**Issue by atharmohammad** [atharmohammad/Code-N-Collab#104]
Client side has some console logs especially in blogs section and profile section , it would be better to not show the data we are getting from backend in console.

**Comment by yasuomaidana** [comment]
I could do it, where are they located??

**Comment by atharmohammad** [comment]
> I could do it, where are they located??

Sure , Change to yjs branch, mostly console logs will be in blogs components , you don't have to setup server for this , so you can use 
``` REACT_APP_BASE_URL = https://code-n-collab-server.herokuapp.com/ ```  
in .env

**Comment by Adnan-shamsi** [comment]
You can use advance search options to get console log in all files
Steps for vs code(if you are using it otherwise you can search online for your editor)
1) just select the parent folder
2) click the search button (on left side)
3) type console.log
4) Then you will see all the files where console.log...  has been written
![Capture](https://user-images.githubusercontent.com/61737425/123503348-30e61b80-d670-11eb-95cf-24018b43b1dd.PNG)

**Comment by yasuomaidana** [comment]
Ok I'll do it right now

**Comment by yasuomaidana** [comment]
Should I left the console.log inside catch??

**Comment by Adnan-shamsi** [comment]
Create a pull request in yjs branch

**Comment by atharmohammad** [comment]
@yasuomaidana Remove console logs and put alert in place of it .. 
```alert("there is some error ! try again!")```.
yjs is development branch currently so make the required changes and pull request on yjs branch  👍

**Comment by yasuomaidana** [comment]
Ok, I got it, I'll do it right now
